apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulsegate

resources:
  - namespace.yaml
  - product-service.yaml
  - api-gateway.yaml
  - admin-dashboard.yaml
  - developer-portal.yaml